name: CI

on:
  pull_request:
    types: ["opened", "reopened", "synchronize"]
  push:
    branches: ["master"]

jobs:
  turborepo-signature:
    name: Example App

    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
      TURBO_REMOTE_CACHE_SIGNATURE_KEY: ${{ secrets.TURBO_REMOTE_CACHE_SIGNATURE_KEY }}
      TURBO_REMOTE_ONLY: true

    steps:
      - name: Clone project
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: "npm"

      - name: Install
        run: npm ci --prefer-offline --include=dev

      - name: Build
        run: npm run build
